server:
  port: 8080
# yml(yaml, 야믈(야멀))
# 시스템 설정에 사용하는 파일
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    # jdbc: java database connector
    # :postgresql - 데이터베이스 엔진
    # //url - 데이터베이스 주소
    # :5432 - 데이터베이스 접속 포트
    # /postgres - 접속할 데이터베이스
    url: jdbc:postgresql://database-1.cpnkgu5gk5eu.ap-northeast-2.rds.amazonaws.com:5432/postgres?currentSchema=partner
    username: postgres
    password: password123!
  jpa:
    show-sql: true
    generate-ddl: true
    # generate-ddl : create SQL 명령어를 자동으로 수행함, auto-migration
  rabbitmq:
    addresses: amqps://b-f5b27dbc-5576-4d4f-849d-03c019cced61.mq.ap-northeast-2.amazonaws.com:5671
    username: rabbitmq
    password: password123!
    
